name: PHP Unit Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.0'  # Puedes ajustar la versión según tus necesidades

    - name: Install dependencies
      run: composer install

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit
      
    - name: Enviar notificación en caso de fallo
      if: failure()
      run: echo "Las pruebas unitarias han fallado Revisa el flujo del proyecto."